services:
  - type: web
    name: cronosflow-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CLIENT_URL
        sync: false
